import os.path

Import("env")


# TEST SUITES

testenv    = env.Clone()

testenv.Append( CPPPATH=['#/test'] )
testenv.Append( LIBPATH=['#/lib/${platform}${platformsuffix}/${buildprofile}'] )
testenv.Append( LIBS=[ 'window', 'test', 'foundation' ] )

if testenv['platform'] == 'linux':
	testenv.Append( LIBS=[ 'dl', 'rt', 'm' ] )
elif testenv['platform'] == 'raspberrypi':
	testenv.Append( LIBS=[ 'bcm_host', 'rt', 'm' ] )
elif testenv['platform'] == 'win32' or testenv['platform'] == 'win64':
	testenv.Append( LIBS=[ 'user32', 'shell32', 'advapi32' ] )
	if testenv['CC'] == 'cl' or testenv['CC'] == 'icl':
		testenv.Append( LINKFLAGS=['/SUBSYSTEM:CONSOLE'])

def makeTest( name ):
    global env
    global testenv
    env[name + 'test'] = testenv.Program( 'test-' + name + '${prgsuffix}', name + '/main.c' )
    testenv.AddPostAction( 'test-' + name + '${prgsuffix}', testenv.Install( '#bin/${platform}${platformsuffix}/${buildprofile}', [ env[name + 'test'] ] ) )

makeTest('all')
makeTest('window')
